Fix GraphCMS/Hygraph Privacy Policy and Terms of Service
OpenTermsArchive/contrib-declarations pull request #1155
Opened 2023-10-21 11:06 UTC by Kissaki

* Rename GraphCMS to Hygraph as per branding change
* Fix Hygraph Privacy Policy and Terms of Service with new URL and selector

See commit descriptions for details.

Replaces my PR #1146, Fixes #1073, #1074

2023-10-22 07:10 UTC, Kissaki commented
> Uncaught Error: The "Hygraph.history" service declaration is malformed and cannot be parsed

What is malformed? I don't see it.

I don't have a local nodejs env and don't want to install one.

2023-12-11 08:46 UTC, clementbiron requested changes
Hi Kissaki, thanks for your contribution :)

The `GraphCMS.json` should not be deleted, it should be empty, see the [renaming a service](https://docs.opentermsarchive.org/contributing-terms/#renaming-a-service) documentation.

```json
{
  "name": "GraphCMS",
  "documents": {}
}
```

2023-12-30 11:47 UTC, Kissaki commented
@clementbiron if you look at the commits in this PR you can see it is not being deleted. The guidance did not exist yet when I originally created this PR; but on December 2nd I force-pushed, presumably with the adjustment to the new guidance - not deleting the file.

I can see the overall diff in GitHub UI "Files Changed" still showing it as being deleted though.

Maybe this is related to force-pushes also not triggering CI too? Does this repository have a configuration that prevents PR updates through force-pushes somehow? Is it a general GitHub issue? *(I am used to force-pushes in GitLab updating MR commit list and overall diff - and the overall diff with a new diff version.)*

2023-12-30 12:05 UTC, Kissaki commented
I tried a few force pushes, main branch merge, etc, but nothing changed what GitHub displays

2023-12-30 15:41 UTC, Kissaki commented
It's a GitHub Actions configuration issue. My suggested fix: https://github.com/OpenTermsArchive/demo-declarations/pull/30

2024-02-06 14:15 UTC, clementbiron commented
Hello,

I'm sorry, I probably didn't make myself clear in my previous review.

You have [renamed](https://github.com/Kissaki/contrib-declarations/commit/9e76c0811dd00f83cdd60eeda7592448b48123db) the `GraphCMS.json` file to `Hygraph.json` and this is not the right thing to do. The `GraphCMS.json` file must continue to be present but it must be [emptied](https://docs.opentermsarchive.org/contributing-terms/#handling-a-terminated-service) of all terms by removing every `<terms type>` entries from the `documents` key in the declaration. A new `Hygraph.json` file is added and completed to track the documents of the renamed service.

We should therefore have the `GraphCMS.json`, `GraphCMS.history.json` and `Hygraph.json` files.

Regarding your problem with launching tests on the IC, we're going to open a pull request based on your proposal, which we think is an acceptable compromise. Thank you very much for reporting the problem and suggesting a solution 🙏

2024-02-06 16:19 UTC, clementbiron requested changes
Hello,

I'm sorry, I probably didn't make myself clear in my previous review.

You have [renamed](https://github.com/Kissaki/contrib-declarations/commit/9e76c0811dd00f83cdd60eeda7592448b48123db) the `GraphCMS.json` file to `Hygraph.json` and this is not the right thing to do. The `GraphCMS.json` file must continue to be present but it must be [emptied](https://docs.opentermsarchive.org/contributing-terms/#handling-a-terminated-service) of all terms by removing every `<terms type>` entries from the `documents` key in the declaration. A new `Hygraph.json` file is added and completed to track the documents of the renamed service.

We should therefore have the `GraphCMS.json`, `GraphCMS.history.json` and `Hygraph.json` files.

Regarding your problem with launching tests on the CI, we [have merged](https://github.com/OpenTermsArchive/demo-declarations/pull/31) a pull request based on your proposal, which we think is an acceptable compromise. Thank you very much for reporting the problem and suggesting a solution 🙏

2024-03-14 06:54 UTC, Kissaki commented
I fixed it according to the renaming guidance.

2024-03-14 07:05 UTC, Kissaki commented on declarations/GraphCMS.json
>    }
`deno fmt` formats it with a newline, so I hope that's fine and doesn't conflict with what I see in the guidance and another terminated declaration file using `{}` without a newline?

2024-03-18 11:26 UTC, clementbiron approved these changes
Thank you very much! 🚀

2024-03-18 11:26 UTC, merged

2024-03-18 20:49 UTC, Kissaki commented on declarations/GraphCMS.json
>    }
I don't have nodejs installed - and don't want to either :)

2024-03-19 08:00 UTC, clementbiron commented on declarations/GraphCMS.json
>    }
I understand, but you can't use `deno fmt` built-in code formatter to lint files.

2024-03-20 08:33 UTC, MattiSG commented on declarations/GraphCMS.json
>    }
Thanks @Kissaki for clarifying your constraint with the runtime 🙂 
I am not very familiar with `deno`. I had in mind it could install and run npm packages. Would you not be able to set up `ota` and run it on `deno`? 🙂
If not, maybe you can at least run `eslint` from `deno`? In this case, the config file to use is [here](https://github.com/OpenTermsArchive/engine/blob/main/.eslintrc.yaml). Hope that helps!

2024-03-20 09:20 UTC, clementbiron commented on declarations/GraphCMS.json
>    }
I've tried `deno task lint` locally and it doesn't work, so it looks like some adaptations to the code base would be necessary.

2024-03-23 22:43 UTC, Kissaki commented on declarations/GraphCMS.json
>    }
[bun](https://bun.sh/) works as an alternative (on win via WSL) for lint. For lint fix it works with `bun lint --fix` (`lint:fix` does not). Specifying service ids didn't seem to work either.

Test doesn't seem to work. *(I may be missing things because of unfamiliarity with the whole nodejs ordeal and bun.)*

*side note: I assume the bun install before is necessary. I find it insane how much, how many packages, it has to pull and how slow it is to do so for some simple linting. - Now I have a 450 MB homedir cache folder? 😱*

Unfortunately, the lint didn't seem to include the schema validation, so in one case (other, new declaration) I had to do fixups from CI anyway.

But at least the `bun lint --fix` will be useful for me going forward.