Update Alibaba.com declaration
OpenTermsArchive/contrib-declarations pull request #1242
Opened 2023-12-02 14:43 UTC by Kissaki

Fixes #1021

2024-01-10 13:56 UTC, clementbiron commented on declarations/Alibaba.com.json
> +        "#app-root article#rule-detail-body"
I'm curious to understand why you don't just use `#rule-detail-body` ?

2024-01-10 13:56 UTC, clementbiron approved these changes

2024-01-10 14:07 UTC, clementbiron commented on declarations/Alibaba.com.history.json
> +    },
```suggestion
},
{
```

2024-01-10 14:09 UTC, clementbiron requested changes
I validated too quickly and missed the formatting error in the history file, which needs to be corrected ;)

2024-01-10 19:56 UTC, clementbiron requested changes
CI tests have failed again. I've made a suggestion that should lint properly the history file. 

You might be interested in using the [`npx ota lint`](https://docs.opentermsarchive.org/#ota-lint) and [`npx ota validate`](https://docs.opentermsarchive.org/#ota-validate) commands.

2024-01-10 19:56 UTC, clementbiron commented on declarations/Alibaba.com.history.json
> +{
```suggestion
    },
    {
```

2024-01-11 17:40 UTC, Kissaki commented
I don't have node installed and specifically don't want to install it :)

2024-01-28 08:48 UTC, Kissaki commented on declarations/Alibaba.com.json
> +        "#app-root article#rule-detail-body"
I don't remember why I chose to. Looking at it again, you are right, that seems like it would be fine, correct, and robust too.

It's possible I wasn't confident only one "rule" block would occur on a page.

2024-01-28 08:49 UTC, Kissaki commented on declarations/Alibaba.com.json
> +        "#app-root article#rule-detail-body"
```suggestion
        "#app-root #rule-detail-body"
```

2024-01-28 08:49 UTC, Kissaki commented on declarations/Alibaba.com.json
> +        "#app-root article#rule-detail-body"
```suggestion
        "#app-root #rule-detail-body"
```

2024-02-06 16:15 UTC, clementbiron commented on declarations/Alibaba.com.json
> +        "#app-root article#rule-detail-body"
Thank you for clarifying. As it stands, the selector looks fine to me :)

2024-02-06 16:17 UTC, merged