Update pixiv privacy policy selector
OpenTermsArchive/contrib-declarations pull request #1499
Opened 2024-06-14 16:09 UTC by afisher3578

2024-06-26 09:41 UTC, MattiSG requested changes

2024-06-26 09:41 UTC, MattiSG commented on declarations/pixiv.json
>        "fetch": "https://policies.pixiv.net/en.html#privacy",
This now redirects, let's store the redirect target 🙂 
```suggestion
      "fetch": "https://policies.pixiv.net/en/privacy_policy.html",
```

2024-06-26 09:41 UTC, MattiSG commented on declarations/pixiv.json
> +        "main"
> I'd personally find it more stable with a more clearly named selector.
```suggestion
        ".terms-block"
```

2024-06-26 09:41 UTC, MattiSG commented on declarations/pixiv.json
> +        "img"
I don't find any image on https://policies.pixiv.net/en/privacy_policy.html, where did you find one? 🙂

2024-06-27 13:04 UTC, afisher3578 commented on declarations/pixiv.json
> +        "main"
Agreed, thanks for pointing that out.

2024-06-27 13:15 UTC, afisher3578 commented on declarations/pixiv.json
> +        "img"
That is correct now looking into it. There are no images. When I ran the ota engine locally and in the web ui the "Master Terms of Use" were displayed which had images. 
<img width="1394" alt="Screenshot 2024-06-27 at 9 09 03 AM" src="https://github.com/OpenTermsArchive/contrib-declarations/assets/92438650/6080f7e8-3b71-4074-a446-3de4309b583a">
<img width="1375" alt="Screenshot 2024-06-27 at 9 09 50 AM" src="https://github.com/OpenTermsArchive/contrib-declarations/assets/92438650/83303563-4337-426e-bc73-747a7cd741b2">

2024-07-03 15:47 UTC, MattiSG approved these changes
Looks perfect, thanks! ✨

2024-07-03 15:47 UTC, merged