Update Viaplay pp & tos declarations
OpenTermsArchive/contrib-declarations pull request #1557
Opened 2024-07-28 17:01 UTC by afisher3578

Fix for #1536 and #1537

2024-08-08 11:39 UTC, MattiSG requested changes
It seems that the terms of service for this streaming service are only available in the locations where they operate directly, i.e. throughout Scandinavia. For example, [in Finland](https://viaplay.fi/fi-fi/terms).
Conversely, the English terms now yield a 404, and manually selecting “UK” as a region shows [a page](https://viaplay.com/gb-en/) stating “In the UK, Viaplay is available through the following partners: Amazon Prime”.
I thus assume that this service used to be available directly in the UK, with English terms, and that they now passed an agreement with Amazon Prime for exclusive distribution in the UK market.

This leaves us with three options:
1. Leave the declaration as it is, waiting for this page to come back one day.
2. Switch to another language in which the terms are still available. In this case, I would suggest Swedish since the company is based in Sweden, so it is the most likely to stay over time.
3. Remove the ToS from the declaration, akin to if the service had been terminated, and track only the Privacy Policy.

I personally have a preference for option 3 as Viaplay as a streaming service in the given jurisdiction seems to have been closed.

2024-08-08 11:39 UTC, MattiSG commented on declarations/Viaplay.json
>        "fetch": "https://viaplay.com/gb-en/terms",
I get a 404 here.

<img width="591" alt="image" src="https://github.com/user-attachments/assets/93b85e59-5d67-4e2d-bbfb-56046cc99ae4">

2024-08-17 06:38 UTC, afisher3578 commented
@MattiSG Thank you for the thorough explanation of the options. I removed the ToS for the declaration. I agree that option 3 would be the best course of action for a service that has been bundled with another service in the UK market.

2024-08-20 12:14 UTC, MattiSG approved these changes

2024-08-20 12:15 UTC, merged