add bredaccess service agreement
OpenTermsArchive/contrib-declarations pull request #3739
Opened 2024-11-10 19:59 UTC by krichtof

FYI, there are [other legal documents](https://www.bred.fr/informations-reglementaires/conditions-generales) for Bred bank.

2024-11-10 20:27 UTC, krichtof commented
I will read the documentation later and will force push after ;)
No rush

2024-11-10 21:59 UTC, krichtof commented
FYI, I was not able to find list of valid terms type in documentation.

2024-11-13 16:29 UTC, Cli4d requested changes
Hi @krichtof,  

Thank you for your contribution! Congratulations on reading the documentation and addressing the errors that arose from our checks—this is impressive for a first contribution.  

I have reviewed your contribution and found no issues with it or the document being tracked. However, I have a few questions regarding the service name. What is the correct correct service name? Should it be "BRED Access" or "Bred Access". Having the accurate service name will help us easily track all contractual documents related to the service and keep them organized.

2024-11-13 16:29 UTC, Cli4d commented on declarations/Bred Access.json
> +  "name": "Bred Access",
```suggestion
  "name": "BRED Access",
```

2024-11-13 16:29 UTC, Cli4d commented on declarations/Bred Access.json
> +  "name": "Bred Access",
The change here in the service name will also reflect in the file name as the service name is used for the service ID as well which is the file name

2024-11-18 15:45 UTC, MattiSG commented on declarations/Bred Access.json
> +  "name": "Bred Access",
I agree @Cli4d. Since it's been a few days since @krichtof replied, please feel free to implement the correction yourself 👍

2024-11-20 00:21 UTC, Cli4d commented on declarations/Bred Access.json
> +  "name": "Bred Access",
Ok I will proceed to make the change and merge

2024-11-27 13:57 UTC, Cli4d approved these changes

2024-11-27 13:58 UTC, Cli4d commented
I have made the necessary changes and I will proceed to merge the contribution. Thank you once again @krichtof

2024-11-27 13:58 UTC, merged