Add linting script and lint files
OpenTermsArchive/contrib-declarations pull request #565
Opened 2022-05-11 13:58 UTC by martinratinaud

Fixes https://github.com/ambanum/OpenTermsArchive/issues/833

2022-05-11 16:20 UTC, MattiSG requested changes
CI should fail upon linting failure.

2022-05-11 16:20 UTC, MattiSG commented on CONTRIBUTING.md
> +In order to ensure consistency across declarationsan repo, all declarations files have to be linted (formatted) properly and homogeneously.
```suggestion
In order to ensure consistency across declarations, all declarations files have to be formatted homogeneously.
```

2022-05-11 16:20 UTC, MattiSG commented on CONTRIBUTING.md
> +In order to achieve this, you can use the following script
```suggestion
In order to achieve this, you can use the following script:
```

2022-05-11 16:20 UTC, MattiSG commented on CONTRIBUTING.md
> +npm run lint [, $service_id …]
```suggestion
npm run lint [ $service_id …]
```

2022-05-12 09:03 UTC, martinratinaud commented
> CI should fail upon linting failure.

It will when `json_lint` branch is merged on master on OTA core

Tests wlll pass on this branch when all declarations in contrib-declarations are fixed

2022-05-12 09:10 UTC, martinratinaud commented on CONTRIBUTING.md
> +npm run lint [, $service_id …]
I reused what was above in the document (written by @Ndpnt).

I believe the goal of this is to explain that you can use this command with OR without any service_id.
Your suggestion does not reflect this possibility I believe. So I will leave it like this unless you believe it's really not understandable.

Let me know

2022-05-12 09:27 UTC, MattiSG commented on CONTRIBUTING.md
> +npm run lint [, $service_id …]
The “optional” part of a command line argument is by convention made clear with the brackets 🙂

The most conventional way to show that there can be 0-to-many arguments would be:

```suggestion
npm run lint [$service_id [, $another_service_id … ]]
```

2022-05-12 09:28 UTC, MattiSG commented on CONTRIBUTING.md
> +npm run lint [, $service_id …]
See https://stackoverflow.com/questions/9725675/is-there-a-standard-format-for-command-line-shell-help-text

2022-05-12 09:29 UTC, MattiSG commented on CONTRIBUTING.md
> +npm run lint [, $service_id …]
If you want, I'm happy for us to move towards explicitly using http://docopt.org as a reference, but let's make this into a dedicated PR that also updates the CONTRIBUTING 🙂

2022-05-12 09:30 UTC, martinratinaud commented on CONTRIBUTING.md
> +npm run lint [, $service_id …]
thanks. I've harmonized this then

2022-05-12 09:32 UTC, MattiSG commented on CONTRIBUTING.md
> +npm run lint [, $service_id …]
I've created https://github.com/ambanum/OpenTermsArchive/issues/848 accordingly, thanks for raising this point! 😊

2022-05-12 09:55 UTC, martinratinaud commented
MErged after talking with @MattiSG

2022-05-12 10:04 UTC, merged