Scalingo's new GTC
OpenTermsArchive/contrib-declarations pull request #669
Opened 2022-10-11 08:11 UTC by omjdi

2022-10-12 13:15 UTC, MattiSG requested changes
Thank you very much for this contribution @omjdi! :smiley:

As the continuous integration tests tell you, the document types (“Terms of Service” etc) you updated are not free-form: in Open Terms Archive, we unify the document types across services, to enable comparing them 🙂 You can find the full list [here](https://github.com/ambanum/OpenTermsArchive/blob/main/src/archivist/services/documentTypes.json).
Unfortunately, that also means Service Level Agreement and Health Data Hosting are currently **not** possible to track. In order to track these documents, we will need to [open a discussion](https://github.com/ambanum/OpenTermsArchive/discussions/categories/document-types) demonstrating that at least three different service providers offer such documents. You can find several examples of such document type addition requests [here](https://github.com/ambanum/OpenTermsArchive/discussions/categories/document-types).

The `select` parts of the documents also have to be updated to reflect the new layout. Unless you know CSS selectors, the easiest would be to use the contribution graphical user interface I had sent you a link to 😉

Our team will take care of fixing these points this time 🙂 @clementbiron, can you please revert the document types changes, update the selectors and remove the document types we cannot track yet?

2022-10-12 14:41 UTC, clementbiron approved these changes

2022-10-12 15:34 UTC, MattiSG commented on declarations/Scalingo.history.json
> +      "validUntil": "2021-08-16T14:36:00.000Z"
Isn't this November? 🤔

https://github.com/OpenTermsArchive/contrib-declarations/issues/45

```suggestion
      "validUntil": "2021-11-16T14:36:00.000Z"
```

2022-10-12 15:34 UTC, MattiSG commented on declarations/Scalingo.history.json
> +      "validUntil": "2021-08-16T14:36:00.000Z"
Isn't this November? 🤔

https://github.com/OpenTermsArchive/contrib-declarations/issues/46

```suggestion
      "validUntil": "2021-11-16T14:36:00.000Z"
```

2022-10-12 15:46 UTC, clementbiron commented on declarations/Scalingo.history.json
> +      "validUntil": "2021-08-16T14:36:00.000Z"
Maybe better to use the date of the last version we got ? https://github.com/OpenTermsArchive/contrib-versions/commit/5fe86743e83b27efbf4783f3e33f2b4e87e4ca83

2022-10-12 15:55 UTC, MattiSG commented on declarations/Scalingo.history.json
> +      "validUntil": "2021-08-16T14:36:00.000Z"
I don't think so: this is the last version, that does not mean this is the [last snapshot](https://github.com/OpenTermsArchive/contrib-snapshots/commits/master/Scalingo/Terms%20of%20Service.html) 🙂 that just means there were no changes recorded in the document since then.

2022-10-12 15:55 UTC, MattiSG commented on declarations/Scalingo.history.json
> +      "validUntil": "2021-08-16T14:36:00.000Z"
We know the URL is incorrect since 16/11. The fact there was no version since 16/08 does not mean we would not be able to regenerate history between 16/08 and 16/11, only that there were no changes recorded.

2022-10-12 16:09 UTC, clementbiron commented on declarations/Scalingo.history.json
> +      "validUntil": "2021-08-16T14:36:00.000Z"
Ok thanks for the clarification, writing history file is really not the easiest part!

2022-10-13 03:44 UTC, martinratinaud approved these changes

2022-10-13 03:46 UTC, martinratinaud commented on declarations/Scalingo.history.json
> +      "validUntil": "2021-08-16T14:36:00.000Z"
In fact, the contribution tool takes care of that for you if you use the URL that is indicated within the GitHub issue.

This will also
Fix #47 
Fix #46 
Fix #45

2022-10-13 08:14 UTC, MattiSG commented
Surprisingly, while the suite passes, tests [fail](https://github.com/OpenTermsArchive/contrib-declarations/actions/runs/3240712355/jobs/5311673225) with the following error:

```
Uncaught error outside test suite:
[45](https://github.com/OpenTermsArchive/contrib-declarations/actions/runs/3240712355/jobs/5311673225#step:5:46)
     Uncaught TypeError: Cannot read property 'pages' of undefined
```

@martinratinaud do you have an idea what's happening there?

2022-10-13 08:45 UTC, martinratinaud commented
@MattiSG yes, it's because I added an entry in history for `Privacy Policy`, but there is not `Privacy Policy` in the declaration file anymore. @Ndpnt can you please check that.

@omjdi please can you tell me if scalingo still have privacy policies?

It seems from this [google search](https://www.google.com/search?q=scalingo+privacy+policy&oq=scalingo+privacy+polic&aqs=chrome.0.69i59j69i57j69i61.5891j0j1&sourceid=chrome&ie=UTF-8) that there are


But [this url](https://scalingo.com/fr/privacy-policy) is a 404

Once I have this answer, I can proceed with the merge

Thanks

2022-10-18 11:11 UTC, martinratinaud commented
Replaced by https://github.com/OpenTermsArchive/contrib-declarations/pull/685 as I made a git mistake and can not force push on your branch

2022-10-18 11:11 UTC, closed without merging

2022-10-19 06:40 UTC, martinratinaud commented
Hi @omjdi 

Declarations are now tracked again and you can [check them here](https://github.com/OpenTermsArchive/contrib-versions/tree/main/Scalingo)

Thanks a lot for your contribution