Fix call to scripts after OTA core update
OpenTermsArchive/contrib-declarations pull request #772
Opened 2023-01-16 05:26 UTC by martinratinaud

All [newly created PR](https://github.com/OpenTermsArchive/contrib-declarations/actions/runs/3855456615/jobs/6570526346) are failing validation as `ota-validate-declarations: not found`

2023-01-16 09:34 UTC, MattiSG requested changes

2023-01-16 09:34 UTC, MattiSG commented on package.json
> +    "@opentermsarchive/engine": "^0.20.0",
This should not be a caret notation until we reach v1.0.0, as only the minor version will upgrade. As it is, this will always update to the latest (and breaking) version.

I personally would be in favour of reaching 1.0.0 on Engine, but as it is, I believe we should use [`~` instead of `^`](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept).

2023-01-16 10:38 UTC, martinratinaud commented
Dup of https://github.com/OpenTermsArchive/contrib-declarations/pull/748/commits/9e254b135591d9df2758bd863eec9d21a2b0bd96

2023-01-16 10:39 UTC, martinratinaud commented
But maybe it should be merged before to prevent all PRs to be in error.

2023-01-17 06:54 UTC, martinratinaud commented
I used `~` to only update automatically on patch releases as minor can still contain breaking changes until we reach 1.0.0

2023-01-17 08:18 UTC, MattiSG approved these changes
LGTM!

2023-01-17 10:12 UTC, merged