Improve readme
OpenTermsArchive/contrib-declarations pull request #836
Opened 2023-03-16 08:38 UTC by clementbiron

Application and adaptation of the [improvements made](https://github.com/OpenTermsArchive/template-declarations/pull/26#issuecomment-1470460781) on the readme template.

2023-03-17 16:21 UTC, MattiSG requested changes

2023-03-17 16:21 UTC, MattiSG commented on README.md
> +These service declarations are consumed by the [Open Terms Archive engine](https://github.com/OpenTermsArchive/engine).
```suggestion
The terms listed in this collection are tracked by the [Open Terms Archive engine](https://github.com/OpenTermsArchive/engine). 
```

2023-03-22 10:24 UTC, MattiSG approved these changes
Thanks @clementbiron!

2023-03-22 10:24 UTC, MattiSG commented on README.md
> +Please note that due to its specific history of being the first instance of Open Terms Archive, before a clear architectural choice for decentralisation was taken, and being mostly based on non-curat
I feel like the link should be more a link to the list of instances than to the documentation of what instances are, WDYT? 🙂 

```suggestion
Please note that due to its specific history of being the first instance of Open Terms Archive, before a clear architectural choice for decentralisation was taken, and being mostly based on non-curated imports of an existing fonds, this scope is unusually large and inconsistently enforced. We strongly encourage contributors to focus on [topical collections](https://opentermsarchive.org/#collections) and use this collection only as a last resort.
```

2023-04-17 12:54 UTC, clementbiron commented on README.md
> +Please note that due to its specific history of being the first instance of Open Terms Archive, before a clear architectural choice for decentralisation was taken, and being mostly based on non-curat
Totally agree

2023-04-17 13:16 UTC, merged